### ISSUE TITLE
Add General Map Support

### ISSUE THREAD

**Issue by davecom** [hectr/MRWorldMapView#1]
This looks awesome, but why support only a single kind of map? If the project included support for SVG or GeoJSON it would be perfect.

**Comment by hectr** [comment]
Hi! Have you checked [FSInteractiveMap](https://github.com/ArthurGuibert/FSInteractiveMap)? It already supports SVG format.

**Comment by davecom** [comment]
Yes I have, it doesn't have as nice an API as your project in my opinion.  Thanks for the pointer though.

**Comment by hectr** [comment]
I like your idea of supporting other map formats :)

In the `develop` branch I've changed the way the map is loaded. Now it should be easier to transform a GeoJson map to a dictionary with the supported format. I think I will go for it in the next few days.

**Comment by davecom** [comment]
Awesome - I think it will take it to the next level and you should then rebrand it as a general purpose maps solution.
